#!/usr/bin/ruby -w

require 'lib/charm-tools'

log "backend relation changed"

def safe_unit_name
  ENV['JUJU_UNIT_NAME'].gsub(/\//, "-")
end

def current_backend
  {
    safe_unit_name => {
      :address => `relation-get private-address`.chomp,
      :port => `relation-get port`.chomp 
    }
  }
end

def active_backends
  backends = local_config_get(:active_backends) || {}
  backends.update(current_backend) # maybe also check the full `relation-list`?
  local_config_set({ :active_backends => backends })
  backends
end

def update_varnish_config
  log "Writing varnish config"
  config_file = '/etc/varnish/default.vcl'
  File.rename(config_file,"#{config_file}.dist") if File.exists?(config_file)
  expand_template_to_file( 'default.vcl.erb',  config_file )
end
update_varnish_config

log "Restart Varnish"
restart_service "varnish"

