#!/usr/bin/ruby -w

require 'lib/charm-tools'

log "backend relation changed"

def current_backends
  # read backends from local config store
  backends = unit_config[:backends]
  # update backends via 'relation-list' and 'relation-get'
  #backends.each do |backend|
  #end
  # save current backends in the local config store
  #write_unit_config
  backends
end

def update_varnish_config
  log "Writing varnish config"
  config_file = '/etc/varnish/default.vcl'
  File.rename(config_file,"#{config_file}.dist") if File.exists?(config_file)
  expand_template_to_file( 'default.vcl.erb',  config_file )
end
update_varnish_config

log "Start Varnish"
restart_service "varnish"

